### ISSUE TITLE
Any plans to add include paths?

### ISSUE THREAD

**Issue by zquintana** [maandree/gpp#1]
I'm consider your project for inclusion on a project I'm working on. Only thing missing is include paths like many other preprocessors have. Standard seems to me `-I {PATH}` to add additional include paths. I've also seen from a few I've tried the ability to have multiple `-I`'s to add multiple inclusion paths for the `#include` directive. Are you planning on adding that?

**Comment by maandree** [comment]
gpp doesn't have `#include` because `.`, `cat`, or `cat | gpp` is sufficient.
If you really need include paths you can add
```sh
locate () (
    IFS=:
    for d in $INCLUDEPATH; do
        if test -f "$d/$1"; then
            printf '%s\n' "$d/$1"
            exit 0
        fi
    done
    printf "Cannot locate %s\n" "$1" >&2
    exit 1
)

include () (
    set -e
    cat -- "$(locate $1)"
)
```
to your files (or in a separate file which you can include with `.`).
